name: flutter_trending_movies
description: "A simple app that shows a trending movies list."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  dio: ^5.6.0
  dartz: ^0.10.1
  mocktail: ^1.0.4
  get_it: ^7.7.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/