name: flutter_trending_movies
description: "A simple app that shows a trending movies list."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  http: ^1.2.2
  dartz: ^0.10.1
  go_router: ^14.2.3
  mocktail: ^1.0.4
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
